### PR TITLE
Add java support

### PR DESCRIPTION
**Pull request by urielsalis**

### CODE REVIEW

**Comment by urielsalis** [comment]
@rohitpaulk any updates?

**Comment by rohitpaulk** [comment]
@urielsalis should have at least one of these merged today! I want to add a language guide for Java like Kotlin (https://docs.codecrafters.io/challenges/language-support/kotlin) + ensure we have a standard format for gitignore etc. 

@urielsalis is there one of these PRs that you'd like me to work on merging first so you can use it? Happy to prioritize that one today

**Comment by urielsalis** [comment]
> @urielsalis should have at least one of these merged today! I want to add a language guide for Java like Kotlin (https://docs.codecrafters.io/challenges/language-support/kotlin) + ensure we have a standard format for gitignore etc.
> 
> @urielsalis is there one of these PRs that you'd like me to work on merging first so you can use it? Happy to prioritize that one today

@rohitpaulk Would love the DNS one! Or SQLite

**Comment by rohitpaulk** [comment]
@urielsalis Okay, I'll do DNS first!

**Pull request merged**
