### PR TITLE
Add support for Dart

### PR DESCRIPTION
**Pull request by DanTup**
Hi!

I was interested in trying CodeCrafters out but Dart isn't supported :-( I thought it might be easy to add, however I wasn't able to get the course-sdk running locally on Windows so I'm trying to debug a little via GitHub actions.

I made the changes in this PR and ran on a fork, but it fails like this:

```
[docker-build] #10 exporting layers 0.5s done
[docker-build] #10 writing image sha256:4e7420d1dc49f9fa50db91d5d6f513f1d1cd96e4f211e98ee6e1b5181a831594 done
[docker-build] #10 naming to docker.io/library/course-sdk-js-tools done
[docker-build] #10 DONE 0.5s

js-tools Docker image built.

Compiling language: dart...
[docker-build] error: Language with slug dart not found

Bun v1.1.13 (Linux x64 baseline)
```

I did add Dart to course-definition, but I don't know if there's another list of languages somewhere I need to update?

I'm not sure the `Dockerfile` is right yet (this is basically what's included at https://hub.docker.com/_/dart/), in particular it doesn't do anything with `/app-cached` (because I didn't really understand what that's for).

If someone can provide some pointers, I'm happy to iterate on this (I assume that once it works for one challenge, it would be fairly straightforward to update others?). @rohitpaulk

Some things that are definitely outstanding:

- [x] Actions are failing on this PR
- [ ] Dockerfile doesn't do anything with /app-cached
- [x] `your_server.sh` is using `dart run` but we compiled a binary in `Dockerfile` and should run that

### CODE REVIEW

**Comment by rohitpaulk** [comment]
Will take a closer look at this tomorrow :) Fixed the primary failure, there's a one-time step needed to allow course-sdk to process new languages: https://github.com/codecrafters-io/course-sdk/commit/523b33b78985566d58327064d0a5407615b28149. I've re-run tests here so you should now see more useful failures (hopefully)

**Comment by DanTup** [comment]
> I've re-run tests here so you should now see more useful failures (hopefully)

I did, thank you! I'll see how much further I can get and post back :)

**Comment by DanTup** [comment]
Dart  is missing from `Uncommenter.REGEX_PATTERNS` in course-sdk. I've opened https://github.com/codecrafters-io/course-sdk/pull/18. Hopefully that gets us a bit further.

**Comment by DanTup** [comment]
@rohitpaulk what is `init.sh`?

```
  - Executing starter repo script

          exec /init.sh: no such file or directory
```

I see it in the starter-code-tester as the script that is run in the container, but it's not clear to me what it should be.

Also, debugging via GH actions was a bit tedious... I'll try to get this set up on a MacBook so I can test locally better.. I'm wondering how much work it might be to fix course-sdk for Windows... is it something you've thought about? Are there known blockers to it?

**Comment by DanTup** [comment]
@rohitpaulk I think this is nearly there now. Bots are green, but a remaining issue is that `./your_server.sh` probably isn't doing the right thing for running locally. Currently, I have:

- `codecrafters-precompile.sh` (written in the Dockerfile) compiles the app with `dart compile` into `./compiled`
- `your_server.sh` runs `exec ./compiled` to execute the code

This works for the tests (and should be faster than running from source or compiling on each test stage), however the instructions say a user can run `./your_server.sh` and that will just run the last compiled version.

Is `./your_server.sh` supposed to run a fast/incremental compile or something? (I'm not familiar enough with the other tools like c++/cmake to understand exactly how they're working).

(on top of that, I don't understand if I need to be doing anything with `/app-cached`?)

**Comment by DanTup** [comment]
Re: the above... Maybe it'd be better if `./your_server.sh` did:

```
if ./compiled exists
  ./compiled
else
  dart run bin/main.dart
```

The uncompiled source might give better errors for users running locally, but still has the benefit of compilation for running through course-sdk. (That said, hopefully while developing most users are just pressing `F5` in VS Code or something and having full debug support!).

**Comment by rohitpaulk** [comment]
> Is ./your_server.sh supposed to run a fast/incremental compile or something? (I'm not familiar enough with the other tools like c++/cmake to understand exactly how they're working).

@DanTup this is pretty wonky right now - `your_server.sh` is both something for users to run the program locally **and** what we use to run tests in remotely. Whenever these tend to be different, our approach has been to use the `precompile.sh` script to override what's inside `your_server.sh`. [Example from Java](https://github.com/codecrafters-io/build-your-own-http-server/blob/01624ac7043584236433f6142954aae115338f64/dockerfiles/java-21.Dockerfile#L15). Super hacky, I know 😃 More on how we're going to properly fix this here: https://forum.codecrafters.io/t/upcoming-change-build-system-overhaul/707. 

I've pushed some commits, overall changes: 

- Add all repository files except README & .git before running `dart pub get`
- Change `your_server.sh` to do both compile + exec compiled so that it works locally
- Changed precompile script to mutate your_server.sh and remove the compile step
- Change the code in `main.dart` to use TCP as a primitive instead of HTTP (the challenge instructions assume that someone is building upon TCP and is implementing HTTP protocol parsing)

@DanTup Could you take a look at this, let me know if all looks good? I'm getting a logo added to the app too, should be good to release as soon as that's done!

**Comment by DanTup** [comment]
@rohitpaulk 

> Could you take a look at this, let me know if all looks good? I'm getting a logo added to the app too, should be good to release as soon as that's done!

Two minor comments/questions, but otherwise seems reasonable to me :)

- Dockerfile is now setting `CODECRAFTERS_DEPENDENCY_FILE_PATHS` files to `vcpkg.json...` at the bottom - is this a copy/paste error (it's set to `pubspec.yaml` at the top which seems correct).
- Should we add `pubspec.lock` also to `CODECRAFTERS_DEPENDENCY_FILE_PATHS`? (if a user commits that file then modifying it without modifying `pubspec.yaml` would indicate a change in resolved versions of dependencies, I think similar to `package-lock.json` for Node

Thanks!

**Comment by rohitpaulk** [comment]
> Dockerfile is now setting CODECRAFTERS_DEPENDENCY_FILE_PATHS files to vcpkg.json... at the bottom - is this a copy/paste error (it's set to pubspec.yaml at the top which seems correct).

🤦 Nice catch, fixed!

> Should we add pubspec.lock also to CODECRAFTERS_DEPENDENCY_FILE_PATHS? (if a user commits that file then modifying it without modifying pubspec.yaml would indicate a change in resolved versions of dependencies, I think similar to package-lock.json for Node

Aha, so **that's** why there was `pubspec.*` in the original PR. I paused a while thinking why that might exist, though it might be to handle things like `.yml` & `.yaml` and then brushed it off. Makes sense now! I just didn't know that `pubspec.lock` was a thing. Added back in now! 

Still waiting on the logo from our designer, will push this live once that's in!

**Comment by DanTup** [comment]
Yep, the relevant files are:

- `pubspec.yaml` - modified by the user to define their dependencies and constraints. always committed
- `pubspec.lock` - generated when they run `pub get` and records the versions of each package being used. May be committed if they want CI and other users to always get the exact same versions (and not committed if they should just re-resolve based on the constraints in `puspec.yaml`
- `.dart_tool/package_config.json` - a map of package names to their location on disk (unlike Node that puts them at `./node_modules`, Dart/Pub put them in a cache folder in the homedir (see [`PUB_CACHE`](https://dart.dev/tools/pub/environment-variables)). Never committed because it contains local absolute paths


> Still waiting on the logo from our designer, will push this live once that's in!

If you haven't already found them, there are some official assets linked on https://dart.dev/brand (there are some rules around using them on that page you'd likely want to review).

If you let me know once it's done, I'd be keen to try working through the stages :) Thanks!

**Comment by rohitpaulk** [comment]
Sorry for the delay here! I thought I'd get back to this after shipping some of the improvements we had planned for compile/run steps. The PR should now be simpler - no weird `precompile.sh` script mangling.

**Comment by rohitpaulk** [comment]
@DanTup I've added you as an alpha tester so you should be able to test this here: https://app.codecrafters.io/courses/http-server/introduction?repo=new. 

Screenshot 2024-07-17 at 16 42 37

(HTTP Server isn't free at the moment so I've also applied a 1 month membership on the house 🙂) 

Just tried the first stage myself and seems to work! 

Screenshot 2024-07-17 at 16 42 17

Screenshot 2024-07-17 at 16 41 43

**Comment by DanTup** [comment]
@rohitpaulk great, thanks! I had a quick go at the first few stages and all seems to be working well. I'll try to get through the rest later in the week. Thanks for the sub too - I started with this one thing it was free, doh!

**Comment by rohitpaulk** [comment]
@DanTup awesome! I think this is good enough to mark as non-alpha then, will do today :)

**Comment by DanTup** [comment]
cool :)

I did get stuck on a step (one that sends concurrent requests) that I need to debug (I can't repro running the `sleep`/`curl` commands locally, so will need to set back up to run the test suite through the SDK), but I don't think it's related to the Dart setup here.

**Pull request merged**
